### ISSUE TITLE
Warning when fetching additional repositories

### ISSUE THREAD

**Issue by crazydef** [microsoft/azure-pipelines-yaml#403] opened 2019-12-03 10:30 UTC
I have our build pipeline setup to fetch a third party repository from git as follows:

```
resources:
  repositories:
  - repository: glm
    type: git
    name: <ourproject>/GLM
    
steps:
- checkout: self

- checkout: glm
  displayName: 'Fetch Libraries/GLM'
  path: s\Libraries\GLM
```

But I'm getting a warning when this is being run:

Repository is current at 'd:\a\1\s\GLM', move to 'd:\a\1\s\Libraries\GLM'.
##[warning]Unable move and reuse existing repository to required location.
Repository will be located at 'd:\a\1\s\Libraries\GLM'.
Syncing repository: GLM (git)

In addition, I'm not entirely happy about the hardcoded `s\` in the front of the `path`, but if I use `$(Build.SourcesDirectory)`, I get an error about the path not allowed to be rooted (or something).

**Comment by doormalena** [comment] 2020-02-18 09:01
We have the same issue in our pipeline. It wants to move the folder before the repository is synced, which is a bit silly at that point as the folder to move does not yet exist.

> ##[debug]Processed: ##vso[plugininternal.updaterepositorypath alias=git://<projectname>/f80bf629-6c75-49e6-ae2c-52565ef40af1@wikiMaster;]d:\a\1\s\includes
##[debug]Repository requires to be placed at 'd:\a\1\s\includes', current location is 'd:\a\1\s\f80bf629-6c75-49e6-ae2c-52565ef40af1'
Repository is current at 'd:\a\1\s\f80bf629-6c75-49e6-ae2c-52565ef40af1', move to 'd:\a\1\s\includes'.
##[debug]Move existing repository 'd:\a\1\s\f80bf629-6c75-49e6-ae2c-52565ef40af1' to 'd:\a\1\s\includes' via staging directory 'd:\a\_temp\_1'.
##[debug]Catch exception during repository move.
##[debug]System.IO.DirectoryNotFoundException: Directory not found: 'd:\a\1\s\f80bf629-6c75-49e6-ae2c-52565ef40af1'
   at Microsoft.VisualStudio.Services.Agent.Util.ArgUtil.Directory(String directory, String name)
   at Microsoft.VisualStudio.Services.Agent.Util.IOUtil.MoveDirectory(String sourceDir, String targetDir, String stagingDir, CancellationToken token)
   at Agent.Plugins.Repository.CheckoutTask.RunAsync(AgentTaskPluginExecutionContext executionContext, CancellationToken token)
##[warning]Unable move and reuse existing repository to required location.
##[debug]Processed: ##vso[task.logissue type=warning;]Unable move and reuse existing repository to required location.
Repository will be located at 'd:\a\1\s\includes'.
Syncing repository: f80bf629-6c75-49e6-ae2c-52565ef40af1 (Git)

**Comment by doormalena** [comment] 2020-02-18 09:39
A workaround for this issue is to add a script before each checkout step to create the desired folder. It will then stop complaining. E.g.

``` yml
      - task: PowerShell@2
        displayName: "Create repository folder (workaround)"
        inputs:
          targetType: inline
          script: |
            New-Item -Path . -Name "$(Build.Repository.Name)" -ItemType "directory" # Equals "self"
          pwsh: true
```

**Comment by ahaleiii** [comment] 2020-02-27 23:31
[Link to code (RepositoryPlugin.cs:161)](https://github.com/microsoft/azure-pipelines-agent/blob/fd55305520c3fe0aa57643935115d8b19f852054/src/Agent.Plugins/RepositoryPlugin.cs#L161). I agree that @doormalena's assessment that it's not checking to see if the `currentRepoPath` exists before attempting to use it. Would like to see this cleaned up (both the behavior and the grammar of the messages).

I don't need to see these warnings on my build when attempting to use multiple repos:
![image](https://user-images.githubusercontent.com/7021001/75496477-40c3f180-598f-11ea-8a3b-2b14ab6227f4.png)

**Comment by afeblot** [comment] 2020-03-05 19:53
It's worse than that:
The fact that it tries to initially check out a repo in the standard location, and then move it to the expected location, leads to running a full git clone, cloning from scratch every time, instead of just cleaning the existing clone and pulling the latest changes.

**Comment by hemisphera** [comment] 2020-03-15 18:47
Any update on this? For me it's just a minor nuisance, but I'd hate to write workaround code just to suppress warnings.

**Comment by sec** [comment] 2020-03-19 13:35
In my case having something like        

> steps:
>           - checkout: self 
>             clean: true  
>             submodules: true
>             persistCredentials: true

on Windows agent - git clone is done into "s\releasename" (something new)
on Linux agent - git clone is done into "s" (desired)

And this break rest of the pipeline on Windows agent, as I have extra subdirectory.
Adding `path: 's'` will produce the warning:
`
Repository is current at 'd:\a\1\s\my_project', move to 'd:\a\1\s'.
##[warning]Unable move and reuse existing repository to required location.
Repository will be located at 'd:\a\1\s'.
`

and this workaround is working for me...

**Comment by Alexees** [comment] 2020-03-26 05:45
Why is it even trying to move? In my case I'm happy with the checkout location and would rather pull changes instead of cloning every time...

**Comment by Alexees** [comment] 2020-03-26 06:29
> A workaround for this issue is to add a script before each checkout step to create the desired folder. It will then stop complaining. E.g.
> 
> ```yaml
>       - task: PowerShell@2
>         displayName: "Create repository folder (workaround)"
>         inputs:
>           targetType: inline
>           script: |
>             New-Item -Path . -Name "$(Build.Repository.Name)" -ItemType "directory" # Equals "self"
>           pwsh: true
> ```

I don't know enough about Powershell yet, but using this the script gives me an error:
![image](https://user-images.githubusercontent.com/32508825/77617066-81ce0800-6f33-11ea-9c2b-19fc2c212a73.png)

**Comment by doormalena** [comment] 2020-03-26 06:35
> 
> 
> > A workaround for this issue is to add a script before each checkout step to create the desired folder. It will then stop complaining. E.g.
> > ```yaml
> >       - task: PowerShell@2
> >         displayName: "Create repository folder (workaround)"
> >         inputs:
> >           targetType: inline
> >           script: |
> >             New-Item -Path . -Name "$(Build.Repository.Name)" -ItemType "directory" # Equals "self"
> >           pwsh: true
> > ```
> 
> I don't know enough about Powershell yet, but using this the script gives me an error:
> ![image](https://user-images.githubusercontent.com/32508825/77617066-81ce0800-6f33-11ea-9c2b-19fc2c212a73.png)

Hint: the indentation of the script contents ;-)

**Comment by Alexees** [comment] 2020-03-26 06:40
Yeah, stupid me. Net to get used to languages with Indentation syntax

**Comment by SimonAlling** [comment] 2020-03-30 14:53
> A workaround for this issue is to add a script before each checkout step to create the desired folder. It will then stop complaining. E.g.
> 
> ```yaml
>       - task: PowerShell@2
>         displayName: "Create repository folder (workaround)"
>         inputs:
>           targetType: inline
>           script: |
>             New-Item -Path . -Name "$(Build.Repository.Name)" -ItemType "directory" # Equals "self"
>           pwsh: true
> ```

Unfortunately, I don't think this works in general. You may not know the name of the repo (and thus the directory to create); your YAML may be a general template to clone any given repository, and/or `checkout` may simply be `self`.

**Comment by tsaibabu4u** [comment] 2020-04-06 16:41
Anyone know to suppress these warnings from console output ?

**Comment by svnscha** [comment] 2020-04-21 20:36
Would love to see a fix for this.

**Comment by rajarshi-singh** [comment] 2020-04-21 20:51
This warning fills up the space on the detail view our pipeline run because there are so many repeated occurrences. It doesn't look. Please provide a fix or provide a way to disable showing warnings in the main pipeline view.

**Comment by djee-ms** [comment] 2020-04-22 14:55
Ping @vtbassmatt randomly, can someone please triage? This issue was opened 5 months ago.

We are also hitting that, why is the checkout step not checking to create the folder, and what are the consequences? Does the checkout step really does a full checkout then move to a different folder? We have a 5+ **minutes** checkout, if the checkout step is not able to do a proper job then we'll reimplement it, but we'd like at least to know.

**Comment by djee-ms** [comment] 2020-04-22 15:48
Confirmed that even with on-prem agents the checkout is done from scratch every single time, that is in our case we are in for 5 minutes (scratch) instead of 10 seconds (incremental), as most submodules in this checkout rarely change. This completely defeats the point of having on-prem agents in the first place, and makes the `path` parameter of the `checkout` step arguably unusable/broken.

**Comment by SimonAlling** [comment] 2020-04-23 07:20
> Confirmed that even with on-prem agents the checkout is done from scratch every single time, that is in our case we are in for 5 minutes (scratch) instead of 10 seconds (incremental), as most submodules in this checkout rarely change. This completely defeats the point of having on-prem agents in the first place, and makes the `path` parameter of the `checkout` step arguably unusable/broken. @doormalena's suggestion does remove the warning, but does not change that.

I think `fetchDepth` might be the solution to your problem:

```yaml
steps:
  - checkout: self
    fetchDepth: 1
  - checkout: another-cool-repo
    fetchDepth: 1
```

**Comment by djee-ms** [comment] 2020-04-23 09:01
@SimonAlling thanks for pointing out that, yes `fetchDepth` can probably help reduce the time spent, I had forgotten about it, I will try it out again see if that helps for us.

I would point however that remains a workaround to a core functionality not working (incremental checkout) AND an _a priori_ bad default behavior (checkout in some folder then move, instead of directly checking out in the right folder; at least that what it looks from the warning message). Also because GitHub does not allow checking out random commits by SHA1, but only named refs, calculating the appropriate `fetchDepth` value can be tricky, as it depends on how far the commit you want to build is from a named ref (usually, branch tip).

**Comment by vtbassmatt** [comment] 2020-04-23 12:23
:wave: sorry for the delay. No one is watching this repository for support issues. You should file this at [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html). I'll update the issue ticket to make it super clear that we aren't actively watching for time-sensitive issues here.

**Closed by vtbassmatt** 2020-04-23 12:23 UTC

**Comment by djee-ms** [comment] 2020-04-23 15:28
This is not acceptable. If you are not monitoring this project then please disable the issue feature and prevent users from opening new issues. There are 251 open issues as we speak, and this means at least as many users waiting for an answer. If you do not intend to reply to them they you should at least say so.

**Comment by djee-ms** [comment] 2020-04-23 17:48
@SimonAlling actually I tried `fetchDepth = 1` and that shaves off 2 minutes, thanks! However I should point that this is brittle; I just had a CI failure related to this, because the pipeline started with the git branch tip at a specific commit, and the Azure agent saved that commit's SHA1, then by the time the checkout was actually executed, some more commits had been pushed to that branch, so when GitHub tried to `git checkout <sha1>` then that commit was not available because the `<sha1>` was several commits behind the branch tip, and only the branch tip was downloaded on the Azure agent due to `fetchDepth = 1`.

**Comment by soccerjoshj07** [comment] 2020-04-23 18:38
@djee-ms Yeah I had the same thing happen to me. I changed it to fetchDepth = 10 and for me it only added a dozen or so seconds more than =1.

**Comment by SimonAlling** [comment] 2020-05-07 08:18
> @SimonAlling actually I tried `fetchDepth = 1` and that shaves off 2 minutes, thanks! However I should point that this is brittle; I just had a CI failure related to this, because the pipeline started with the git branch tip at a specific commit, and the Azure agent saved that commit's SHA1, then by the time the checkout was actually executed, some more commits had been pushed to that branch, so when GitHub tried to `git checkout <sha1>` then that commit was not available because the `<sha1>` was several commits behind the branch tip, and only the branch tip was downloaded on the Azure agent due to `fetchDepth = 1`.

Oof – nasty one! Will be keeping an eye out for that.

**Comment by rdtechie** [comment] 2020-06-14 19:19
Created an support issue here: https://developercommunity.visualstudio.com/content/problem/1077497/unable-move-and-reuse-existing-repository-to-requi.html

**Comment by JtMotoX** [comment] 2023-05-05 20:30
Thanks everyone for the workaround.

Here is what did it for me.
```yaml
- { bash: mkdir $(Build.SourcesDirectory)/automation >/dev/null 2>&1 || true, displayName: Create repository folder (workaround) } # https://github.com/microsoft/azure-pipelines-yaml/issues/403
- { checkout: templates, path: automation, fetchDepth: 1 }
- { checkout: self, path: s, fetchDepth: 1 }
```

**Comment by sda399** [comment] 2024-03-11 13:45
I created the directories like @JtMotoX  did.
no luck, still having the warnings.
is there a clean way to work with multiple branches of the same repository? I am using '- checkout'

**Comment by DuyTran-TomTom** [comment] 2024-04-11 14:22
I tried to create the directory before checking out too, it still didn't work 😕 
```yaml
- checkout: self
  path: s
- bash: |
    mkdir $(Build.SourcesDirectory)/templates
    ls -alt
  displayName: Create templates directory
- checkout: templates
  path: s/templates
```
