### ISSUE TITLE
How to give permission to scripts to run git commands

### ISSUE THREAD

**Issue by cdmihai** [microsoft/azure-pipelines-yaml#248] opened 2019-07-03 00:59 UTC
I need to run a powershell script that runs various git read operations (clone, checkout, etc) on external public github repos (not the repo running the CI job). This does not seem to work, and documentation seems outdated: https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/git-commands?view=azure-devops&tabs=yaml

What makes it work in the old style non-yaml pipeline is ticking "allow scripts to access the OAuth token", but I have no idea how to do this with yaml.

yaml failing output:
```
git : Note: checking out '7bd12afef8fe3b88d0798974c6e060f76f043b8e'.
At line:1 char:1
+ git checkout 7bd12afef8fe3b88d0798974c6e060f76f043b8e
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Note: checking ...060f76f043b8e'.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
##[debug]Exit code: 1
##[debug]Leaving Invoke-VstsTool.
##[error]PowerShell exited with code '1'.
##[debug]Processed: ##vso[task.logissue type=error]PowerShell exited with code '1'.
##[debug]Processed: ##vso[task.complete result=Failed]Error detected
##[debug]Leaving D:\a\_tasks\PowerShell_e213ff0f-5d5c-4791-802d-52ea3e7be1f1\2.151.1\powershell.ps1.
```

old style pipeline:
```
Note: checking out '7bd12afef8fe3b88d0798974c6e060f76f043b8e'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 7bd12afe Integrate solution dependencies in static graph
```

**Comment by cdmihai** [comment] 2019-07-03 01:19
I tried the suggestion in https://github.com/microsoft/azure-pipelines-agent/issues/1833 but it still does not work, same failure.

```
variables:
  system.accesstoken: $(System.AccessToken)
```

**Comment by matteotumiati** [comment] 2019-08-29 18:15
Have you tried with this?

```
- task: MyTask'
  inputs:
    ...
  env:
    SYSTEM_ACCESSTOKEN: $(system.accesstoken)
```

**Comment by cdmihai** [comment] 2019-08-29 18:16
Yes, but not luck.

**Comment by matteotumiati** [comment] 2019-08-31 15:16
In the first post you mention that you need to do operations on "external public github repos", so I don't think you need the access token from the build agent. 

I made this yaml template and it's running fine on my own agent:

```
steps:
  - task: PowerShell@2
    displayName: Clone repository
    inputs:
      targetType: inline
      script: |
        cd "C:\Program Files\Git\cmd\"
        git.exe clone https://github.com/microsoft/azure-pipelines-yaml.git "$(Build.SourcesDirectory)\Azure-Pipelines\" -q

  - task: PowerShell@2
    displayName: Show repo root content
    inputs:
      targetType: inline
      script: |
        cd "$(Build.SourcesDirectory)\Azure-Pipelines\"
        Get-ChildItem -Path .
```

The first powershell task is just cloning this repository and the second one is checking that all the files from the root folder are actually there.

**Comment by matteotumiati** [comment] 2019-09-16 12:44
@cdmihai have you had the chance to try (and verify it works) so we can close the issue? Are there any more issues on your side?

**Comment by cdmihai** [comment] 2019-09-16 22:36
I verified and it still repros. The git commands succeed from the inline powershell scripts, but fail if I move the same commands inside a .ps1 file.

Here's the yaml file: https://github.com/microsoft/MSBuildStaticGraphTester/pull/11/files#diff-fec826feae04e51c0d94076385408bdc
It runs git clone and checkout from inline scripts, then calls `GitOperations.ps1` with the same git commands.

`GitOperation.ps1`: https://github.com/microsoft/MSBuildStaticGraphTester/pull/11/files#diff-c0bb709ca67793575a3579e34a4c38bb

Job link: https://dev.azure.com/ms/MSBuildStaticGraphTester/_build/results?buildId=36301&view=logs&j=4d2c9369-8a9d-5a07-59e2-01301bbb1099

**Comment by matteotumiati** [comment] 2019-09-20 16:56
I think this is related to the way PowerShell handles git output, but I don't know the root cause and I cannot tell you more details of what's happening to be honest. 

By the way, to solve your issue, you can just add the '-q' (--quiet) on the checkout command:

```
Write-Output "====before git checkout"
& "C:\Program Files\Git\cmd\git.exe" checkout -q ee8294b5597fe21ca5c44c8fd4c142d27fcec2cb
Write-Output "====after git checkout"
```

Alternatevely you can try to set the environment variable _GIT_REDIRECT_STDERR_ to redirect the outputs for every git command as written in the [documentation](https://git-scm.com/docs/git#Documentation/git.txt-codeGITREDIRECTSTDERRcode).

For some commands, that might be ok, for others you may want to have more details on what is happening with git, but the solution depends on the command you need to run. For example, if you do a clone, you can use the option '-q' along with '--progress' to see the details.

**Comment by cdmihai** [comment] 2019-09-23 20:47
Quieting the git output made it work. Thanks!
Somehow, because those scripts run successfully in other build environments, I never thought about git's output having such an effect. I wonder why ADO topples over it.

**Closed** 2020-04-26 09:41 UTC
Labels: dont-fear-the-reaper
