### ISSUE TITLE
How to set "Tag source: 'on success'" in YAML

### ISSUE THREAD

**Issue by lanluu** [microsoft/azure-pipelines-yaml#325] opened 2019-09-09 09:32 UTC
Hi,

I could not find any template/doc about the configuration for **"checkout" -> "Tag source: 'on success'"** in **YAML**. Is it possible?

![image](https://user-images.githubusercontent.com/3998945/64519962-73046880-d2f5-11e9-8302-7de8781ee7e7.png)

Thank you for your feedbacks!
BR
Lan

**Comment by FizzBuzz791** [comment] 2019-09-12 05:21
This is a duplicate of #139

**Closed** 2020-04-26 09:41 UTC
Labels: dont-fear-the-reaper

**Comment by konstantinmiller** [comment] 2021-09-06 08:58
Could you please provide a link to this topic in the Developer Community? I couldn't find it.

**Comment by wwestrop** [comment] 2021-09-30 21:07
@konstantinmiller [It is here](https://developercommunity.visualstudio.com/idea/1007477/missing-gui-option-create-git-tag-after-successful.html)
