### ISSUE TITLE
Can't Authorize YAML Build Task to Use Service Connection

### ISSUE THREAD

**Issue by TingluoHuang** [microsoft/azure-pipelines-yaml#31] opened 2018-10-30 03:24 UTC
copy from: https://github.com/Microsoft/azure-pipelines-agent/issues/1809

When I try to build my source using the yaml below;

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'xxxredactedxxx'
  projectfolder: 'xxxredactedxxx'

steps:
- script: docker build -f $(projectfolder)/Dockerfile -t $(imageName):$(build.buildId) -t $(imageName):latest .
  displayName: 'docker build'

- task: AmazonWebServices.aws-vsts-tools.ECRPushImage.ECRPushImage@1
  displayName: 'Push Image: '
  inputs:
    awsCredentials: 'AWS'
    regionName: 'eu-west-1'
    sourceImageName: '$(imageName)'
    repositoryName: '$(imageName)'
    autoCreateRepository: true
I get the following error;

Job phase1: Step input awsCredentials references service connection AWS which could not be found. The service connection does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz

I confirm I have a service connection named AWS.

I tried reading the link in the error message. However, the article doesn't show any directions on how to authorize the build to use the service conneciton.

**Comment by CesarRN** [comment] 2018-10-30 14:47
Hello @TingluoHuang 

I can't solve my problem
https://github.com/Microsoft/azure-pipelines-agent/issues/1809#issuecomment-434274247

Thanks

**Comment by TingluoHuang** [comment] 2018-10-30 14:52
@CesarRN can you share your AzurePipeline(VSTS) account name or the pipeline definition url that facing the problem? i can try check our telemetry see what error i can find.

**Comment by ericsciple** [comment] 2018-10-30 14:55
@vijayma ?

**Comment by chrismade** [comment] 2018-11-26 21:01
I came across the same issue and posted in [stackoverflow](https://stackoverflow.com/questions/53401927/vsts-anybody-managed-to-use-secure-file-in-azure-pipelines-yml/53488887) - assuming that this is an intended behaviour or a bug that won't fix easily - is there a chance to extend the troubleshooting section here https://aka.ms/yamlauthz - this is the shortcut which appears in the error message - so that people using build pipelines have a chance to fix it - e.g. by adding or changing variables ?

**Comment by DerAlbertCom** [comment] 2018-12-06 12:14
Is there any way to authorize and serverEndpoint for a FtpUpload@1 in a JobTemplate? I cannot get this to work with all the known workarounds.

**Comment by tsuga** [comment] 2018-12-24 13:00
Any update?

**Comment by chris31389** [comment] 2019-03-25 12:09
Any movement on this? 

I've just tried adding this task to my build.yml and i'm getting an error in by PR Build `Unable to queue Build`

```
Job Job: Step input azureSubscription references service connection My Subscription which could not be found. The service connection does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz.
```

```
- task: AzureResourceGroupDeployment@2
  displayName: 'Validate ARM Template'
  inputs:
    azureSubscription: 'My Subscription'
    resourceGroupName: 'dev'
    location: 'West Europe'
    csmFile: 'src/Arm/azuredeploy.json'
    csmParametersFile: 'src/Arm/azuredeploy.parameters.json'
    deploymentMode: Validation
```

**Comment by vijayma** [comment] 2019-04-09 16:31
You now have an option in the service connection/variable group/secure file management experience to "authorize all pipelines". If you select that option, then you won't see this error any more. 

If you do not want to authorize all pipelines, then we are rolling out another fix for this now/next week. The build that failed will have a banner giving you an option to fix it right there by authorizing the pipeline (and then start another build).

**Comment by dapalmi** [comment] 2019-05-21 15:30
The "Authorize" Button did nothing to me. After queuing the same error appeared...

**Comment by vijayma** [comment] 2019-05-23 14:43
1. Check whether the service endpoint from the error message shows up in the list of service endpoints (under project settings -> Pipelines -> service connections).
2. Check whether you are a member of the user role on that service connection.

**Closed** 2019-05-23 14:43 UTC

**Comment by tomas-lipensky** [comment] 2019-12-10 17:02
I had a same issue. Yaml pipeline reference an environment. After clean up of service connections I have deleted service connection related to the environment. Than the error during the pipeline was confusing. I had to recreated the environment, which was referenced by Yaml pipeline and it solved the issue.

**Comment by jake-martin** [comment] 2020-04-14 19:15
I just ran into this issue and fixed it by doing [this work-around](https://github.com/microsoft/azure-pipelines-agent/issues/1809#issuecomment-424136235), which says to edit the pipeline in classic view. I simply set my agent to clean the source before building and saved.

@vijayma I have authorized the service connection for all pipelines, but I still had this issue, so I'm not sure that fixed the issue.

**Comment by tomagb** [comment] 2020-04-20 11:35
I've also run into this issue. Unfortunately the work arounds mentioned didn't work. I had to recreate a new pipeline using the Docker Registry template and let the wizard to generate the service connection and the yaml. After that I've edited the yaml to suit my old one and I also was able to move it in a subfolder.
Probably is worth mentioning that my setup involves a template for building containers in a subfolder and pipeline in the repo's root which uses the templates.

**Comment by MarkHaroldson** [comment] 2020-05-27 15:04
I Just went through all of the work arounds as well with no luck.

- Why have an "authorize resource" button if it doesn't work?
- Also is there a "yaml" sandbox where I can work through connection issues like this without having to re invoke the entire pipeline?

**Comment by jorg-snyders** [comment] 2020-08-17 16:35
I've the same issue here as well. I've altered my YAML files by dividing two region based servers into two deployments instead of one and now it complains about this.
`Encountered error(s) while parsing pipeline YAML:
Job job_deploy_server: Step  input azureSubscription references service connection $(ServicePrincipalRegion) which could not be found. The service connection does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz.`

Adding a variable doesn't do the trick like [this work-around](https://github.com/microsoft/azure-pipelines-agent/issues/1809#issuecomment-424136235), and retricting permission on the pipeline and giving it back the permission didn't solve it either.

Also, the authorize button appears, but doesn't do anything other then give a message that it gave the authorization, which it didn't.

**Comment by chalcrow** [comment] 2020-09-14 23:59
By the way, it's easy to miss the button that allows you to authorize!

![image](https://user-images.githubusercontent.com/8063058/93149578-07d84800-f73a-11ea-9d8b-5fe716963bd1.png)

**Comment by HollyGram9307** [comment] 2020-11-13 12:42
Try change the service connection name to the sub name and try again. I worked for me.

**Comment by Sanoobk** [comment] 2020-12-24 15:58
There should be an option to configure the Pipeline to the new or different Service Connection.
**Scenario**: I delete an existing Service Connection used by Pipeline. Created a new Service Connection with a different name. But the Pipeline is still referring to old name of the Service Connection object. 

As mentioned by @HollyGram9307 , creating the new Service Connection with the old name is a workaround. May not be a suitable workaround for all cases.

**Comment by FaCoffee1984** [comment] 2021-01-28 15:36
> By the way, it's easy to miss the button that allows you to authorize! Clicking this can fix the issue
> 
> ![image](https://user-images.githubusercontent.com/8063058/93149578-07d84800-f73a-11ea-9d8b-5fe716963bd1.png)

**This doesn't work.** When you rerun failed jobs or run the pipeline again, the same error message (and the same button) appears.

**Comment by lohithgn** [comment] 2021-01-29 12:10
I agree with @FaCoffee1984  ... i created a fresh pipeline for xamarin. and facing the same issue. I get the notification. i click the button authorize resources. we get notification resources authorized. if we queue the build again - same issue occurs again ... how to proceed ?

**Comment by grvillic** [comment] 2021-10-19 03:42
Like other people here, the "Authorize resources" button didn't work in my case. Nevertheless, the workaround that fixed it for me was editing the service connection and reverting changes:

1. Edit Service connection: change name (copy the old name) and uncheck "Grant Access permission to all pipelines"
2. Click on "Verify and save"
3. Edit Service connection: revert name (paste old name) and check "Grant access permission" to all pipelines
4. Click on "Verify and save"

There must be a bug somewhere that when someone clicks "Grant access permission to all pipelines" it only grants it to the existing pipelines at that point in time.

**Comment by packnologynz** [comment] 2021-11-24 02:22
I also can't get this working. I've tried all the suggested fixes above and still doesn't work. This issue was originally posted 3 years ago, so I guess it's not going to be resolved. I'm using GitHub as my repo, with the Pipelines integration app. I can get it working with a DevOps Git repo, but not with GitHub. Looks like I'll need to ditch Pipelines and move to GitHub Actions.

**Comment by Janevski** [comment] 2022-08-17 23:43
> > By the way, it's easy to miss the button that allows you to authorize! Clicking this can fix the issue
> > ![image](https://user-images.githubusercontent.com/8063058/93149578-07d84800-f73a-11ea-9d8b-5fe716963bd1.png)
> 
> **This doesn't work.** When you rerun any failed jobs or run the pipeline again, the same error message (and the same button) appears. It says that all resources have been authorised after clicking, but the error message is still there.

Same here.
The subscription exists in service connections, it has all pipeline permissions, yet this authorization error still happens.

I figured out Microsoft wants us to suffer and that's the reason.
And a way of fixing their issie is not using their platform.

**Comment by jmlp1** [comment] 2022-09-07 08:56
> By the way, it's easy to miss the button that allows you to authorize! Clicking this can fix the issue
> 
> ![image](https://user-images.githubusercontent.com/8063058/93149578-07d84800-f73a-11ea-9d8b-5fe716963bd1.png)

I was using my  subscription Id on the yaml, changing to the same name to the service connection just worked, go figure!, Thanks for the post, I was in a real sucking pickle and crazy loop

**Comment by calohmn** [comment] 2022-11-17 10:54
> Like other people here, the "Authorize resources" button didn't work in my case. Nevertheless, the workaround that fixed it for me was editing the service connection and reverting changes:
> 
>     1. Edit Service connection: change name (copy the old name) and uncheck "Grant Access permission to all pipelines"
>     2. Click on "Verify and save"
>     3. Edit Service connection: revert name (paste old name) and check "Grant access permission to all pipelines"
>     4. Click on "Verify and save"

Editing the service connection and just modifying the description fixed the issue for me. 
("Grant Access permission to all pipelines" is unchecked in my case.)

**Comment by damnedOperator** [comment] 2022-12-01 09:56
None of the workarounds or proposed solutions work for me. Referencing a service connection through YAML templating. The name resolution works correctly, but it can't find the SC from the pipeline - authorizations are all set correctly.

**Comment by FaCoffee1984** [comment] 2022-12-01 11:44
@damnedOperator If you are using group variables, could you try this? It has fooled me more than once:

- In DevOps, go to Pipelines
- Hover over the three dots on the right hand side of your pipeline and click 'Edit'
- Hover over the three dots in the top-right corner, next to `Variables` and `Run`, and click 'Triggers'
- Click on 'Variables', which is to the left of 'Triggers'
- Click on 'Variable Groups' and then, in the middle of the screen, click on 'Link variable group'
- Choose the relevant variable group which includes your Service Connection and select 'Link' at the bottom
- Re-run your pipeline and it should work

**Comment by damnedOperator** [comment] 2022-12-01 12:37
> @damnedOperator If you are using group variables, could you try this? It has fooled me more than once:
> In DevOps, go to Pipelines
> Hover over the three dots on the right hand side of your pipeline and click Edit
> Hover over the three dots in the top-right corner, next to Variables and Run, and click Triggers
> Click on Variables, which is to the left of Triggers
> Click on Variable Groups and then, in the middle of the screen, click on Link variable group
> Choose the relevant variable group which includes your Service Connection and select Link at the bottom
> Re-run your pipeline and it should work
> 
> 

We use the Service connections from the Project Properties so this is of no use to us - but deleting the SC and recreating it seemed to work.

**Comment by IainD925** [comment] 2023-10-02 13:49
> @damnedOperator If you are using group variables, could you try this? It has fooled me more than once:
> 
> * In DevOps, go to Pipelines
> * Hover over the three dots on the right hand side of your pipeline and click `Edit`
> * Hover over the three dots in the top-right corner, next to `Variables` and `Run`, and click `Triggers`
> * Click on `Variables`, which is to the left of Triggers
> * Click on `Variable Groups` and then, in the middle of the screen, click on `Link variable group`
> * Choose the relevant variable group which includes your Service Connection and select `Link` at the bottom
> * Re-run your pipeline and it should work

Caught me out plenty of times with Release pipeline, didn't event think of it for Build pipeline.  Working, thank-you!

**Comment by kislow** [comment] 2024-04-03 07:17
Microsoft should've changed the naming scheme for `task.inputs.azureSubscription`.

**Example:**

```sh
steps:
- task: AzureCLI@2
  inputs:
     azureSubscription: <SERVICE_CONNECTION_NAME> # Note: azureSubscription != subscriptionName or subscriptionId
    scriptType: bash
    scriptLocation: inlineScript
    workingDirectory: src
    inlineScript: |
      set -ex
      echo "Listing resource groups..."
      az group list
  displayName: 'List resource groups'
```


Azure docs highlights the following:  [azureSubscription: # string. Alias: connectedServiceNameARM. Required. Azure Resource Manager connection.](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-cli-v2?view=azure-pipelines#syntax)

They `connectedServiceNameARM` alias can be used instead of azureSubscription. Not sure why they just didn't name it `serviceConnectionName`. Either way, to solve this `The service connection does not exist or has not been authorized for use` ensure you use the service connection name instead of your subscriptionName or subscriptionID.

Personally, to make things clearer, I'd go with connectedServiceName rather than azureSubscription:

```sh
steps:
- task: AzureCLI@2
  inputs:
     connectedServiceNameARM: <SERVICE_CONNECTION_NAME> # Note: azureSubscription != subscriptionName or subscriptionId
    scriptType: bash
    scriptLocation: inlineScript
    workingDirectory: src
    inlineScript: |
      set -ex
      echo "Listing resource groups..."
      az group list
  displayName: 'List resource groups'
```
