### ISSUE TITLE
Simple way to redeploy a given build to a given environment

### ISSUE THREAD

**Issue by williamayerst** [microsoft/azure-pipelines-yaml#333] opened 2019-09-20 14:30 UTC
I have a fairly robust pipeline for continuous deployment. One of the biggest issues we have however, is that after we cannot specify a particular build number to redeploy to a given environment (for example, if there was a transient error, or we want to perform some UAT on a previous build).

This was available in the classic releases view out of the box, and was very useful.

Is this something we can achieve easily with pipelines in some way I'm not familiar with?

Thanks!

**Comment by fmms** [comment] 2019-09-29 14:22
i am missing this very much as well. We used it all the times with classic pipelines.

**Comment by fmms** [comment] 2019-09-29 15:07
This is a duplicate of / very similar to  #260 as far as i can see.

**Comment by matteotumiati** [comment] 2019-10-01 16:25
This feature is now available as part of Sprint 158 released on September 23rd:
https://github.com/microsoft/azure-pipelines-yaml/issues/260#issuecomment-537115178

**Comment by escalonn** [comment] 2019-10-01 20:10
Only partially available, from what I can tell. Redeploy apparently is only possible when there was an error in the stage, not possible when the stage succeeded.

**Comment by matteotumiati** [comment] 2019-10-01 20:16
It is possible! 
I had to remove some sensitive data from the following image, but you can see that a button to re-run a successful state is indeed available:

![aaa](https://user-images.githubusercontent.com/3147566/65997138-1aaa2c00-e499-11e9-8887-e52c2b28d212.PNG)

**Comment by spr0ut** [comment] 2020-03-09 11:11
What's missing from the above image (and obviously, microsoft's documentation) is that this is only visible once the "expand" button is selected:
![image](https://user-images.githubusercontent.com/30391853/76207911-92be1000-61f6-11ea-973a-b9d1d1f32e53.png)
Given that the entire target area of the build stage takes you through to the pipeline details view, this took a while to realise! Very frustrating. The option to re-run should be available from the detail view as well, and **not** hidden away.

**Closed** 2020-04-26 05:41 UTC
Labels: dont-fear-the-reaper
