### ISSUE TITLE
Use complex parameters in scripts

### ISSUE THREAD

**Issue by hbuckle** [microsoft/azure-pipelines-yaml#293] opened 2019-08-08 08:50 UTC
It would be great if there was a way to use complex template parameters in scripts, I was thinking the easiest way could be a convert to json expression

Example:

```yaml
parameters:
  complexobject:
    key1: value1
    key2: value2

steps:
  - pwsh: |
      $complexobject = '${{ convertToJson(parameters.complexobject) }}' | ConvertFrom-Json
      Write-Host $complexobject.key1
      Write-Host $complexobject.key2
```

I can achieve this for array parameters by doing a join then a split, but can't find anything for maps.

**Comment by ggirard07** [comment] 2020-02-03 21:25
Duplicate of #427 or vice versa... but there is more details in the linked issue anyway :)

**Closed** 2020-04-26 06:41 UTC
Labels: dont-fear-the-reaper
