### ISSUE TITLE
Cannot submit IPA file to AppStore when AppStore requires iOS 17 SDK or later

### ISSUE THREAD

**Issue by cuonggosu97** [microsoft/azure-pipelines-yaml#611] opened 2024-07-11 10:13 UTC
I'm getting an error when trying to submit my app to the AppStore. But I get the following unexpected error:

[Application Loader Error Output]: ERROR: Asset validation failed (90725) SDK version issue. This app was built with the iOS 16.2 SDK. All iOS and iPadOS apps must be built with the iOS 17 SDK or later, included in Xcode 15 or later, in order to be uploaded to App Store Connect or submitted for distribution. 

I used vmImage: 'macos-latest'

My xCode build code is as follows:
task: Xcode@5
 displayName: 'Build IPA'
 inputs:
 actions: 'build'
 configuration: 'Release'
 sdk: 'iphoneos'
 ...
 packageApp: true
 exportPath: 'output'
 signingOption: 'manual'
 signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
 provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'

**Comment by DmitriiBobreshev** [comment] 2024-07-11 11:05
Hi @cuonggosu97, as I see from [the images page](https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md), Xcode 15 installed only on [macos-14 ](https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md)images. 
You could try to set macos-12/13 where the default version [xcode is 14](https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md#tools). 
If you still will be getting the error please create an issue in [runner-images repo](https://github.com/actions/runner-images/issues) or in the [pipeline-task repo](https://github.com/microsoft/azure-pipelines-tasks/issues) if you believe that the problem is in the Xcode task.

For now, I'm closing this issue as not related to azure-pipeline-yaml repository.

**Closed by DmitriiBobreshev** 2024-07-11 11:05 UTC
Labels: Area: Yaml, triage
